name: Globalization
on:
  pull_request_target:
    branches:
      - master
jobs:
  globalization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: G11n Radar
        uses: citrix-workspace/g11n-scan@feature-PACMAN-3175
        with:
          skip: 'bundles/coming_soon/,buundles/'
          slack-channel: gs-pipeline-notification
          slack-access-token: ${{ secrets.SLACKBOT_TOKEN }}
